### ISSUE TITLE
Setting resource requests via Subscription doubles the intended request resources

### ISSUE THREAD

**Issue by dlydiard** [redhat-cop/namespace-configuration-operator#138]
In an attempt to set resource requests and limits for the operator via Subscription:
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: namespace-configuration-operator
  namespace: namespace-configuration-operator
spec:
  channel: alpha
  name: namespace-configuration-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
  startingCSV: namespace-configuration-operator.v1.2.4
  config:
    env:
      - name: ALLOW_SYSTEM_NAMESPACES
        value: "false"
    resources:
      requests:
        memory: 3Gi
        cpu: 1000m
      limits:
        memory: 3Gi
```

We noticed that the resulting Deployment sets the requests for both the `kube-rbac-proxy` and the `manager` containers.
In normal operation the `kube-rbac-proxy` uses considerably less resources than the `manager` controller. Is there a way to configure these resource requests separately per container?

```
containers:
    - name: kube-rbac-proxy
       resources:
        limits:
          memory: 3Gi
        requests:
          cpu: '1'
          memory: 3Gi
    - name: manager
       resources:
        limits:
          memory: 3Gi
        requests:
          cpu: '1'
          memory: 3Gi
```
