### ISSUE TITLE
Add support for template-based label/annotation matching

### ISSUE THREAD

**Issue by tamoreton** [redhat-cop/namespace-configuration-operator#193]
## Use case

When creating namespace configurations, there are scenarios where we want to match labels/annotations based on dynamic values derived from the namespace itself. 

For example, a common pattern is to have ArgoCD instances managing namespaces where the instance name is derived from the namespace name:

```yaml
metadata:
  name: my-project
  labels:
    argocd.argoproj.io/managed-by: my-project-argo
```

Currently, we can't create a NamespaceConfig that matches based on this pattern without requiring additional trigger labels.

## Proposed solution

Add a new field to the NamespaceConfig spec for template-based matching:

```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: gitops-config
spec:
  labelMatchTemplate:
    argocd.argoproj.io/managed-by: "{{ .Name }}-argo"
  templates:
    - objectTemplate: |
        apiVersion: v1
        kind: Namespace
        metadata:
          name: {{ .Name }}-argo
```

This would allow the operator to:

1. Evaluate the template expressions against the namespace
1. Check if the resulting key-value pairs match the namespace's actual labels/annotations

## Benefits

- More intuitive configurations that can use self-referential patterns
- Reduction in redundant labeling (no need for separate trigger labels)
- Better support for common patterns like ArgoCD management where instance names follow a convention
- More maintainable configurations as relationships are more explicit

## Alternatives considered

1. Using standard label selectors with `Exists` operator - less precise, can't validate naming convention
1. Using separate trigger labels - works but adds unnecessary complexity
1. Using regexp matching - possible but less intuitive and harder to maintain

Would this feature be valuable to the project? Happy to provide more details or discuss alternative approaches.

**Comment by raffaelespazzoli** [comment]
your alternative #1 would be my recommendation for this use case. Can you explain in which sense it is less precise?

**Comment by tamoreton** [comment]
If I just check that a label with the key `argocd.argoproj.io/managed-by` exists, then the NamespaceConfig may unintentionally be applied to non-tenant namespaces. So then we need to have some additional selector, e.g. `myplatform.com/tenant-gitops-namespace: tenant-app-argo`, but then a team has to have _both_ selectors on their namespace, and they need to match each other (and `argocd.argoproj.io/managed-by` will refer to a namespace that does not yet exist).

**Comment by raffaelespazzoli** [comment]
I am not sure I fully understand the use case. But it looks like you need to be able to do two things:
1. discriminate between tenant and system namespaces
2. for tenant namespaces, apply a namespace config.

It also seems like you are trying to discriminate between tenant and system namespace with a label `argocd.argoproj.io/managed-by` that does not really contain that information as you use it for both tenant and non-tenant namespaces. Assuming you have a good reason for doping that (as opposed to simply add another label: `tenant: "true"`, for example), then you'll need to have either whitelist (of tenant namespaces) or a blacklist (of system namespaces). With the list information you can add a second selector that actually matches only the namespaces you want. 
Finally I don't understand your initial example: you cannot create namespaces in a namespace config. You are supposed to create manifests within the matched (and pre-existing) namespaces.

**Comment by tamoreton** [comment]
The use case is a platform-as-a-service where each tenant gets their own Argo CD server. The Argo CD server is in its own namespace so that it doesn't use the same resource quota as the resources in the namespace itself, and also because teams may want to be able to configure separate access control for deployment and development. So it's not that we're using the namespace configuration operator to create the namespace, it's that we're using it to create an additional, companion namespace.

For realising this with selectors I tried these options:

1. Have `myplatform.com/tenant-gitops: "true"` as the required label. This would automatically generate an additional namespace named `<namespace-name>-argo`. But you'd also have to remember to put `argocd.argoproj.io/managed-by: `<namespace-name>-argo` on the namespace or I assume it wouldn't work correctly in difficult-to-reason-about ways.
2. Have `argocd.argoproj.io/managed-by` as the required label key, and use its value to generate the name of the Argo CD namespace—so then any Argo CD-managed namespace gets configured in this way. But using a selector which is a label that is defined by a different operator this might inadvertently target namespaces which aren't tenant namespaces.
3. Require both of the above. So you need to have `myplatform.com/tenant-gitops: "true"` _and_ `argocd.argoproj.io/managed-by` on the namespace to get the `NamespaceConfig`; i.e.
    ```yaml
    spec:
      labelSelector:
        matchExpressions:
          - key: argocd.argoproj.io/managed-by
            operator: Exists
      matchLabels:
        myplatform.com/tenant-gitops: "true"
    ```

This proposal is essentially to create an option 4, to be able to do this with a single namespace.

I went with option 3 for now, but the `NamespaceConfig` resource in Argo CD had an error on it like, "the object has been modified; please apply your changes to the latest version and try again" (other `NamespaceConfig`s were fine), and when trying to delete/force sync the resource, it actually deleted all the resources in the openshift-gitops namespace and the openshift-gitops namespace itself got stuck in a `Terminating` state 🧐

**Comment by ephico2real2** [comment]
**Disclaimer:**  I'm an OpenShift platform engineer  (former RHCA Level 1 - but active Red Hat Openshift Cert ) with extensive experience in enterprise Openshift and Kubernetes deployments and AI-assisted development workflows. I leverage advanced prompt engineering techniques for rapid, precise code development and I am currently working on contributing to namespace-configuration-operator improvements locally.

@tamoreton - This is a really interesting enhancement request that addresses a common GitOps pattern. I've been working on some template processing improvements in the operator and wanted to share some thoughts on your proposal.

Valid Use Case ✅

Your multi-tenant ArgoCD scenario is a legitimate pain point. The self-referential pattern where `my-project → my-project-argo → argocd.argoproj.io/managed-by: my-project-argo ` is indeed common in platform engineering, and the current workarounds (dual selectors, trigger labels) do add unnecessary complexity.

Technical Feasibility
The good news is that the operator already has robust template processing infrastructure that could support this feature. I've recently been working on template filtering mechanisms in GroupConfig that demonstrate the operator can handle dynamic pattern matching and template evaluation efficiently.

What would be needed:


•  New `labelMatchTemplate/annotationMatchTemplate` fields in `NamespaceConfig `CRD
•  Template evaluation during namespace selection (similar to existing template processing)
•  Integration with current label/annotation selector logic

•  The current NamespaceConfig supports both labelSelector AND annotationSelector
•  I was thinking about API consistency - if we add `labelMatchTemplate`, should we also add `annotationMatchTemplate`?

**Implementation Approach:** 

I'd suggest a phased approach:

1. API Design Phase - Community input on the exact field structure and behavior
2. Prototype - Leverage existing template engine for proof-of-concept  
3. Performance Testing - Ensure template evaluation doesn't impact reconciliation performance
4. Production Validation - Test with real GitOps scenarios

```yaml
spec:
  # Both fields needed for API consistency with existing labelSelector/annotationSelector
  labelMatchTemplate:
    argocd.argoproj.io/managed-by: "{{ .Name }}-argo"
    platform.company.com/tenant: "{{ .Name }}"
    
  annotationMatchTemplate:
    deployment.kubernetes.io/revision: "{{ .Name }}-v1"
    argocd.argoproj.io/sync-wave: "{{ .Labels.priority | default \"0\" }}"
    
  # Alternative: More flexible matching conditions  
  templateMatching:
    - type: "label"
      key: "argocd.argoproj.io/managed-by"
      valueTemplate: "{{ .Name }}-argo"
      operator: "Equals"
    - type: "annotation"  
      key: "deployment.version"
      valueTemplate: "{{ .Name }}-{{ .Labels.version }}"
      operator: "Equals"
```

Looking forward to your thoughts!
