### ISSUE TITLE
Error:  non-standard resources (without the spec field) are not supported.

### ISSUE THREAD

**Issue by jtudelag** [redhat-cop/namespace-configuration-operator#27]
Altough the rolebinding object is created properly in the matched namespaces,
the NamespaceConfig object reports a failure status: `non-standard resources (without the spec field) are not
    supported` 

Any ideas?

```
kind: NamespaceConfig                                                                                                                                                                         
metadata:                                                                                                                                                                                                                                                                                                                                      
  finalizers:                                                                                                                                                                                 
  - namespace-config-operator                                                                                                                                                                 
  generation: 1                                                                                                                                                                               
  name: kronos-admins-group-rbac                                                                                                                                                              
  namespace: namespace-configuration-operator                                                                                                                                                                                                                                                                                                
spec:                                                                                                                                                                                         
  resources:                                                                                                                                                                                  
  - apiVersion: authorization.openshift.io/v1                                                                                                                                                 
    groupNames:                                                                                                                                                                               
    - kronos-admins                                                                                                                                                                           
    kind: RoleBinding                                                                                                                                                                         
    metadata:
      name: kronos-admins-group
    roleRef:
      name: cluster-admin
    subjects:
    - kind: Group
      name: kronos-admins
  selector:
    matchLabels:
      kronos-rbac: kronos-admins
status:
  lastUpdate: 2019-11-18T10:58:17Z
  reason: "2 errors occurred:\n\t* non-standard resources (without the spec field)
    are not supported\n\t* non-standard resources (without the spec field) are not
    supported\n\n"
  status: Failure
```
