### ISSUE TITLE
Service accounts and tokens issue

### ISSUE THREAD

**Issue by a1ex-var1amov** [redhat-cop/namespace-configuration-operator#85]
Hi everyone,

We tried to use the Operator to create service accounts across our projects in OpenShift.
After a few weeks, we found an enormous number of secrets for our services accounts.
The same picture across all non-system namespaces. 

So the reason looks like this: when a user creates a new project/namespace, the operator makes new tokens for the same service accounts around all non-system projects. That means each project creation generates a new SA for the new project, creates tokens for this SA, then changes tokens for all SAs with the same names within all non-system projects.

So one new project creation makes ~100 secrets. All the previous keys, of course, are still there. So you can see hundreds and thousands of secrets per project very soon.

Can you please check and let me know if our namespaceconfig is wrong or we are facing the bug:

The namespace config:

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: ns-config-service-accounts
spec:
  annotationSelector: {}
  labelSelector:
    matchExpressions:
    - key: type
      operator: Exists
  templates:
  - excludedPaths:
    - .metadata
    - .status
    - .spec.replicas
    - .imagePullSecrets
    - .secrets
    objectTemplate: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: sa-edit
        namespace: {{ .Name }}
      imagePullSecrets:
      - name: gitlab-access
  - excludedPaths:
    - .spec.replicas
    - .metadata
    - .status
    - .secrets
    objectTemplate: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: sa-view
        namespace: {{ .Name }}
  - excludedPaths:
    - .status
    - .spec.replicas
    - .metadata
    - .secrets
    objectTemplate: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: view-sa-view
        namespace: {{ .Name }}
      subjects:
      - kind: User
        name: sa-view
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: view
        apiGroup: rbac.authorization.k8s.io
  - excludedPaths:
    - .spec.replicas
    - .metadata
    - .status
    - .secrets
    objectTemplate: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: edit-sa-edit
        namespace: {{ .Name }}
      subjects:
      - kind: User
        name: sa-edit
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: edit
        apiGroup: rbac.authorization.k8s.io
```

Thank you all!
