### ISSUE TITLE
howto lookup data?

### ISSUE THREAD

**Issue by davidkarlsen** [redhat-cop/namespace-configuration-operator#87]
I have a namespaceconfig:
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: fss-apps
spec:
  labelSelector:
    matchLabels:
      app.kubernetes.io/managed-by: clout
  templates:
  - objectTemplate: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: admin
        namespace: {{ .Name }}
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin
      subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: '{{ (lookup "v1" "Namespace" "" "{{ .Name }}").Annotations.openshift.io/requester }}'
```

how can I lookup the annotation openshift.io/requester from the namespace I create the role within, in order to set the user? I tried digging in the code to find how the templating works, but it wasn't obvious to me.

**Comment by davidkarlsen** [comment]
So part of this question is really how is the input-context? Since this is a `NamespaceConfig` it's the namespace, but what keys does it have? everything under metadata, and keys uppercased?

**Comment by davidkarlsen** [comment]
I tried:

```
{{- define "requester" }}
{{- $ns := lookup "v1" "Namespace" "" "{{ .Name }}" -}}
{{- index $ns.metadata.annotations "openshift.io/requester" }}
{{- end }}
```

but then I get "error calling index: index of untyped nil".

**Comment by raffaelespazzoli** [comment]
all of it is governed by golang templating rules. Also the namespace is already passed as the root parameter of the the template so you should simply be able to do:
```
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: '{{ index .metadata.annotations "openshift.io/requester" }}'
```

**Comment by raffaelespazzoli** [comment]
can we close this?

**Comment by davidkarlsen** [comment]
Yes. Thanks for the info.

**Comment by davidkarlsen** [comment]
Is it the namespace which is the root parameter, or the *metadata* of the namespace?
Since .Name can be used, it looks like the metadata object.

I've tried:
* `{{ index .Labels "jaeger-instance" }}`
* `{{ index .Metadata.Labels "jaeger-instance" }}`
* `{{ index .metadata.labels "jaeger-instance" }}`

to no avail

**Comment by davidkarlsen** [comment]
something had locked itself up with the ns config resource, I deleted it and reapplied and then it works fine.

For others this syntax works:
```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: jaeger
spec:
  labelSelector:
    matchLabels:
      fss.tietoevry.com/jaeger-enabled: "true"
  templates:
  - objectTemplate: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: {{ index .Labels "fss.tietoevry.com/jaeger-instance" }}-trusted-ca
        namespace: {{ .Name }}
        labels:
          config.openshift.io/inject-trusted-cabundle: "true"
          app.kubernetes.io/managed-by: namespace-configuration-operator
  - objectTemplate: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: name: {{ index .Labels "fss.tietoevry.com/jaeger-instance" }}-service-ca
        name: jaeger-service-ca
        namespace: {{ .Name }}
        annotations:
          service.beta.openshift.io/inject-cabundle: "true"
        labels:
          app.kubernetes.io/managed-by: namespace-configuration-operator
```
