### ISSUE TITLE
Failed: OwnNamespace InstallModeType not supported when upgrading to 1.0.0

### ISSUE THREAD

**Issue by gforster** [redhat-cop/namespace-configuration-operator#88]
Getting the following error after cluster upgrade:

`Failed: OwnNamespace InstallModeType not supported, cannot configure to watch own namespace`

Operator version 1.0.0

**Comment by raffaelespazzoli** [comment]
please remove the namespace from the operatorgroup. It should look something like this:
```yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operator-sdk-og
  namespace: namespace-configuration-operator
spec: {}
 ```
