### ISSUE TITLE
podPresets support 

### ISSUE THREAD

**Issue by archerbj** [redhat-cop/namespace-configuration-operator#9]
Hi, I am trying to use PodPresets to automatically inject time zone environment variable into all pods in Openshift 3.11. 

and I found PodPresets are removed in Openshift 3.11. 

This blog `https://blog.openshift.com/controlling-namespace-configurations/` 
 leads me here. 

Since podPresets resource type no longer exists in openshift 3.11 k8s APIserver,so i think CR `namespaceconfig` probably won't bring it back. 

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: ecocloud-pod-env
spec:
  selector:
    matchLabels:
      ecocloud-pod: "true"
resources:
- apiVersion: settings.k8s.io/v1alpha1
  kind: PodPreset
  metadata:
    name: default-podpreset
  spec:
    env:
    - name: TZ
    selector: {}
```

May I get some help for getting PodPreset back or implementing env auto injection ?
